Provide a command-line compiler (as its own npm package)
Input files can be in any extension, and the
output will just be `sameFileName.tpl`.

NOTE: chai and mocha were added as deps because otherwise it
would throw:

$ ./node_modules/ts-node/dist/bin.js src/main.ts

/Users/andres/Documents/Code/ivy-bitcoin/ivy-compiler/node_modules/ts-node/src/index.ts:329
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'chai'. (2688)
Cannot find type definition file for 'mocha'. (2688)
    at getOutput (/Users/andres/Documents/Code/ivy-bitcoin/ivy-compiler/node_modules/ts-node/src/index.ts:329:15)
    at Object.compile (/Users/andres/Documents/Code/ivy-bitcoin/ivy-compiler/node_modules/ts-node/src/index.ts:515:11)
    at Module.m._compile (/Users/andres/Documents/Code/ivy-bitcoin/ivy-compiler/node_modules/ts-node/src/index.ts:402:43)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/andres/Documents/Code/ivy-bitcoin/ivy-compiler/node_modules/ts-node/src/index.ts:405:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at Object.<anonymous> (/Users/andres/Documents/Code/ivy-bitcoin/ivy-compiler/node_modules/ts-node/src/bin.ts:145:12)